version: '3.8'

services:

  db:
    image: postgres:15
    container_name: adserver_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: adserver_backend
    restart: on-failure
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi/src:/app/src
      - ./fastapi/sqlalchemy_db:/app/sqlalchemy_db
      - ./fastapi/alembic.ini:/app/alembic.ini
      - ./fastapi/.env:/app/.env
    command: uvicorn src:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pg_data:
